name: Trims
version: '${version}'
main: winlyps.trims.Trims
api-version: '1.20'
authors: [Winlyps]
permissions:
  trims.use:
    description: Allows the player to use the /trims command.
    default: op
commands:
  trims:
    description: Apply custom trims to leather helmets.
    usage: /trims <material>
    permission: trims.use